# Generated by Django 4.2.7 on 2023-11-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TenderProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('proposal_summary', models.TextField()),
                ('additional_sections', models.ManyToManyField(related_name='additional_sections', to='proposals.proposalsection')),
                ('financing', models.ManyToManyField(related_name='financing_sections', to='proposals.proposalsection')),
                ('project_planning', models.ManyToManyField(related_name='project_planning_sections', to='proposals.proposalsection')),
            ],
        ),
    ]
